event-handling:
  # Option that tells the engine to get any response from the controllers and wrap them in the
  # JSON envelope structure with "success" flag and the content property ("error" or "data").
  # In such scenario status 419 is converted to OK and the only way to tell that there was error
  # is to check the value of the "success" property.
  wrapResponse: true

  # Options enabling the event capturing capabilities.
  # If you specify enabled as false, the event information will not be captured and you will effectively
  # turn off the event handling mechanism altogether
  capture:
    enabled: true
    templateId: true
    timing: true
    message: true
    causes: true
    context: true
    howToFix: true
    exceptionInfo: true
    stackTrace: true
    location: true

  # Options of the message that is returned to the REST caller
  restResponse:
    templateId: true
    timing: true
    message: true
    causes: true
    context: true
    howToFix: true
    exceptionInfo: true
    stackTrace: false
    location: true

  # Options specifying if the message should be written
  # to the log and what information should be recorded
  log:
    enabled: true
    templateId: true
    timing: true
    message: true
    causes: true
    context: true
    howToFix: true
    exceptionInfo: true
    stackTrace: true
    location: true

  # Console output features
  console:
    enabled: true
    format: JSON
    multiLine: true
    templateId: true
    timing: true
    message: true
    causes: true
    context: true
    howToFix: true
    exceptionInfo: true
    stackTrace: false
    location: true

  templates:
    -
      templateId: "msg00"
      message: "Terrible thing just happened, context: %s"
      
    -
      templateId: "msg01"
      message: "Terrible thing just happened (no context)"
      possibleCauses:
        - "not sure what"
      howToFix:
        - "Write the code again"
        - "Do nothing"
    -
      templateId: "msg02"
      message: "Some error has happened. Please look at the listed messages for clues."

    -
      templateId: "msg03"
      message: "Problem #2 has happened."